// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// InitializeRouter is implemented in providers.go for Monetization Phase 0–1 wiring.
