// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"

	httpadapter "github.com/arifin2018/splitbill-arifin.git/internal/adapter/http"
	"github.com/arifin2018/splitbill-arifin.git/internal/config"
	"github.com/arifin2018/splitbill-arifin.git/internal/service"
)

func InitializeRouter(ctx context.Context, cfg *config.Config) (*httpadapter.Router, error) {
	log, err := provideLogger(cfg)
	if err != nil {
		return nil, err
	}
	uploader, err := provideStorage(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	extractor, err := provideExtractor(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	svc := service.NewSplitbillService(uploader, extractor, log)
	handler := httpadapter.NewSplitbillHandler(svc, log)
	return httpadapter.NewRouter(handler), nil
}
