// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2": {
            "post": {
                "description": "Upload a receipt image and extract detailed splitbill information including items, store details, totals, and transaction information using OCR and AI",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Splitbill"
                ],
                "summary": "Extract splitbill information from receipt image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Receipt image file (jpg, jpeg, png)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully processed receipt",
                        "schema": {
                            "$ref": "#/definitions/domain.SplitbillResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Failed to process receipt",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "Error uploading image"
                }
            }
        },
        "domain.Item": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Nasi Goreng"
                },
                "price": {
                    "type": "string",
                    "example": "25000.00"
                },
                "quantity": {
                    "type": "string",
                    "example": "2"
                },
                "total": {
                    "type": "string",
                    "example": "50000.00"
                }
            }
        },
        "domain.Currency": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "IDR"
                },
                "confidence": {
                    "type": "string",
                    "example": "high"
                },
                "name": {
                    "type": "string",
                    "example": "Indonesian Rupiah"
                },
                "symbol": {
                    "type": "string",
                    "example": "Rp"
                }
            }
        },
        "domain.Language": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "id"
                },
                "confidence": {
                    "type": "string",
                    "example": "high"
                },
                "name": {
                    "type": "string",
                    "example": "Indonesian"
                }
            }
        },
        "domain.SplitbillResult": {
            "type": "object",
            "properties": {
                "currency": {
                    "$ref": "#/definitions/domain.Currency"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Item"
                    }
                },
                "language": {
                    "$ref": "#/definitions/domain.Language"
                },
                "store_information": {
                    "$ref": "#/definitions/domain.StoreInformation"
                },
                "totals": {
                    "$ref": "#/definitions/domain.Totals"
                },
                "transaction_information": {
                    "$ref": "#/definitions/domain.TransactionInfo"
                }
            }
        },
        "domain.StoreInformation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Jl. Sudirman No. 123, Jakarta"
                },
                "email": {
                    "type": "string",
                    "example": "info@restaurant.com"
                },
                "npwp": {
                    "type": "string",
                    "example": "12.345.678.9-012.345"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+62812345678"
                },
                "store_name": {
                    "type": "string",
                    "example": "Restaurant ABC"
                }
            }
        },
        "domain.Tax": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "5000.00"
                },
                "dpp": {
                    "type": "string",
                    "example": "95000.00"
                },
                "name": {
                    "type": "string",
                    "example": "PPN"
                },
                "service_charge": {
                    "type": "string",
                    "example": "0.00"
                },
                "total_tax": {
                    "type": "string",
                    "example": "5000.00"
                }
            }
        },
        "domain.Totals": {
            "type": "object",
            "properties": {
                "change": {
                    "type": "string",
                    "example": "5000.00"
                },
                "discount": {
                    "type": "string",
                    "example": "0.00"
                },
                "payment": {
                    "type": "string",
                    "example": "105000.00"
                },
                "subtotal": {
                    "type": "string",
                    "example": "95000.00"
                },
                "tax": {
                    "$ref": "#/definitions/domain.Tax"
                },
                "total": {
                    "type": "string",
                    "example": "100000.00"
                }
            }
        },
        "domain.TransactionInfo": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "02/08/2025"
                },
                "time": {
                    "type": "string",
                    "example": "19:30"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "TXN123456789"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Splitbill API",
	Description:      "API untuk mengekstrak informasi splitbill dari gambar struk menggunakan OCR dan AI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
